### ISSUE TITLE
Dell PFS Update Extractor v5.1 doesn't work on Dell Optiplex 7090 BIOS

### ISSUE THREAD

**Issue by flipphos** [platomav/BIOSUtilities#10]
1. I tried on Dell Optiplex 7080 BIOS v1.0.7 and it worked.

2. I also tried on the latest Optiplex 7080 BIOS v1.5.1, (file name: OptiPlex_7090_1.5.1.exe), which gives the following info:
*** Dell_PFS_Extract.exe

    Error: This is not a Dell PFS update image!

*** OptiPlex_7090_1.5.1.exe

    Extracted Dell PFS 1 > OptiPlex_7090_1.5.1 > Utilities section!

        Extracted Dell PFS 2 > BuffaloRkl_15.0.35.2028_EVT_BUFFALO_64 v1.5.1 > Utilities section!

Error: Dell PFS Update Extractor v5.1 crashed, please report the following:

Traceback (most recent call last):
  File "Dell_PFS_Extract.py", line 1245, in <module>
  File "Dell_PFS_Extract.py", line 407, in main
  File "Dell_PFS_Extract.py", line 513, in pfs_section_parse
  File "Dell_PFS_Extract.py", line 732, in pfs_extract
  File "Dell_PFS_Extract.py", line 513, in pfs_section_parse
  File "Dell_PFS_Extract.py", line 790, in pfs_extract
  File "Dell_PFS_Extract.py", line 1055, in pfs_file_write
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\Dell BIOS\\Dell Optiplex 7090 BIOS\\V1.5.1\\OptiPlex_7090_1.5.1.exe_extracted\\Firmware\\2 BuffaloRkl_15.0.35.2028_EVT_BUFFALO_64 v1.5.1\\Firmware\\2 BuffaloRkl_15.0.35.2028_EVT_BUFFALO_64 v1.5.1 -- 1 System BIOS with BiosGuard v1.5.1.bin'

Press enter to exit

**Comment by platomav** [comment]
I cannot reproduce this. OptiPlex_7090_1.5.1.exe works perfectly fine on my side. Make sure the downloaded file is complete and that there are no path restrictions (permissions, AV scan etc).
