### ISSUE TITLE
Dell PFS Update Extractor - not work in windows 7

### ISSUE THREAD

**Issue by Ciber-SLasH** [platomav/BIOSUtilities#35]
Hi!
Why "Dell PFS Update Extractor" only support Python 3.10? 3.10 not work in W7, but W7 is good OS for work.
I compile "Dell_PFS_Extract.py" to EXE in 3.8.1 (last work in W7), but this utility bad work in W7 on file: [Precision_3570_Latitude_5530_1.2.1.exe](https://drive.google.com/file/d/1ftLvsIO6j1VfHoTmYbVTxjNXuaNbz8Ps/view?usp=sharing)
```
Dell PFS Update Extractor v6.0_a16

*** Precision_3570_Latitude_5530_1.2.1.exe

    Extracting Dell PFS 1 > Precision_3570_Latitude_5530_1.2.1 > Utilities

    Extracting Dell PFS 1 > Precision_3570_Latitude_5530_1.2.1 > Firmware

        Extracting Dell PFS 2 > D_BIOS_Package_Tool_Ver1.2.0_Precision_3570_Latitude_5530_ADL_1.2.1
v1.2.1 > Firmware

Error: Utility crashed, please report the following:

Traceback (most recent call last):
  File "Dell_PFS_Extract.py", line 1067, in <module>
  File "common\templates.py", line 93, in run_utility
  File "Dell_PFS_Extract.py", line 250, in pfs_pkg_parse
  File "Dell_PFS_Extract.py", line 396, in pfs_section_parse
  File "Dell_PFS_Extract.py", line 626, in pfs_extract
  File "Dell_PFS_Extract.py", line 396, in pfs_section_parse
  File "Dell_PFS_Extract.py", line 695, in pfs_extract
  File "Dell_PFS_Extract.py", line 1009, in pfs_file_write
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\tmp\\Precision_3570_Latitude_5530_1.2.1.exe_extracted\\Firmware\\2D_BIOS_Package_Tool_Ver1.2.0_Precision_3570_Latitude_5530_ADL_1.2.1v1.2.1\\Firmware\\2D_BIOS_Package_Tool_Ver1.2.0_Precision_3570_Latitude_5530_ADL_1.2.1 v1.2.1 -- 1 System BIOS with BiosGuard v1.2.1.bin

Press enter to exit
```

**Comment by platomav** [comment]
The utilities required Python 3.10 for new features, capabilities and performance improvements. Thus, whatever Python 3.10 requires in terms of OS, that's what the utilities need. I'll go ahead and close this as not planned.
